* configure.ac.pamphlet: Check GCL tarball dependency.         * configure.in: Regenerate.

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -20540,8 +20540,16 @@ echo "$as_me: error: erroneous value for --enable-gcl" >&2;}
 fi
 
 fi
-## We need to build our own GCL is none is avalaible
+## We need to build our own GCL if none is avalaible
 if test -z $axiom_lisp; then
+    ## A lisp may not be available AND the GCL source may also
+    ## be missing.  Instruct user to either build one or get
+    ## the dependencies from our website.
+    if test ! -d ${srcdir}/gcl; then
+       { { echo "$as_me:$LINENO: error: OpenAxiom needs GCL.  Either separately build one, or get the dependency tarball from OpenAxiom website." >&5
+echo "$as_me: error: OpenAxiom needs GCL.  Either separately build one, or get the dependency tarball from OpenAxiom website." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
     # Extract the first word of "gcl", so it can be a program name with args.
 set dummy gcl; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -20602,6 +20610,13 @@ echo "$as_me: error: --disable-gcl specified but no GCL image found" >&2;}
 
        ## No Lisp image was specified and none was available from
        ## the build environment; build GCL from OpenAxiom source.
+       ## User may explicilty specify --enable-gcl, but may be missing
+       ## the dependency tarball.
+       if test ! -d ${srcdir}/gcl; then
+          { { echo "$as_me:$LINENO: error: The OpenAxiom dependency tarball is missing; please get it from our website." >&5
+echo "$as_me: error: The OpenAxiom dependency tarball is missing; please get it from our website." >&2;}
+   { (exit 1); exit 1; }; }
+       fi
        AXIOM_LISP='$(axiom_build_bindir)/gcl'
        axiom_all_prerequisites="$axiom_all_prerequisites all-gcl"
        axiom_include_gcl=yes
